name: chat_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  provider: ^6.1.5
  overlay_support: ^2.1.0
  shared_preferences: ^2.5.3
  # New dependencies for enhanced features
  intl: ^0.20.2
  cached_network_image: ^3.3.1
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  flutter_slidable: ^3.0.1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  #  adaptive_icon_background: "assets/background.png"
  #  adaptive_icon_foreground: "assets/foreground.png"
  remove_alpha_ios: true

flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

  fonts:
    - family: Battambang
      fonts:
        - asset: assets/fonts/Battambang-Regular.ttf
        - asset: assets/fonts/Battambang-Bold.ttf
          weight: 700
